### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### canacel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "89c7ab8c784f4c97a0ad4bd1c42adfd6",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/3be4a3558745437e91e255f214ca3c65